name: retech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  flutter_launcher_icons: ^0.11.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf 
          style: normal
    - family: SairaStencil
      fonts:
        - asset: assets/fonts/SairaStencilOne-Regular.ttf 
          style: normal

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  min_sdk_android: 21